package clientes;

import model.entidades.Usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author pc
 */
public class inicioCliente extends javax.swing.JFrame {

    /**
     * Creates new form inicioCliente
     */
    private static Usuario usuario;
    public inicioCliente(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtDocumento2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consultar = new javax.swing.JButton();
        imagen5 = new javax.swing.JLabel();
        imagen6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        consultar2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        comboEdad = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        comboMotivo = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtMascota = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        comboVet = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        comboHora = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        consultar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDocumento1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtVeterinario = new javax.swing.JTextField();
        imagen3 = new javax.swing.JLabel();
        imagen4 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 3, 20)); // NOI18N
        jButton1.setText("AGENDAR");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 3, 20)); // NOI18N
        jButton2.setText("AGENDA");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jButton3.setFont(new java.awt.Font("Tw Cen MT", 3, 20)); // NOI18N
        jButton3.setText("HISTORIAL");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jButton4.setFont(new java.awt.Font("Tw Cen MT", 3, 20)); // NOI18N
        jButton4.setText("INICIO");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel9.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/44.png"))); // NOI18N
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jButton5.setFont(new java.awt.Font("Tw Cen MT", 3, 20)); // NOI18N
        jButton5.setText("INICIO");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jPanel9.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel18.setText("VETERINARIA");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel21.setText("ANIMALSLOVE");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 180, 30));

        jLabel36.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSanti/44.png"))); // NOI18N
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 100));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 850, 80));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 730, 330));
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 470));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("inicio", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Tw Cen MT", 3, 50)); // NOI18N
        jLabel39.setText("Historiales medicos");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel35.setText("Nro de documento:");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        txtDocumento2.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtDocumento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumento2ActionPerformed(evt);
            }
        });
        jPanel8.add(txtDocumento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 190, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Dueño", "Tipo", "Edad", "Motivo", "Fecha", "Mascota", "Veterinario"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 680, 260));

        consultar.setBackground(new java.awt.Color(196, 154, 237));
        consultar.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        jPanel8.add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 100, 30));
        jPanel8.add(imagen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 760, 652));
        jPanel8.add(imagen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 380, 650));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 22, 16, 636));

        jTabbedPane1.addTab("tab4", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultar2.setBackground(new java.awt.Color(196, 154, 237));
        consultar2.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        consultar2.setText("Consultar");
        consultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar2ActionPerformed(evt);
            }
        });
        jPanel5.add(consultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 100, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 3, 50)); // NOI18N
        jLabel16.setText("AGENDAR CONSULTAS");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        txtDocumento.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        jPanel5.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, 30));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel23.setText("Nro de telefono:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 180, -1));

        comboTipo.setBackground(new java.awt.Color(255, 255, 255));
        comboTipo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Hamster", "Conejo", "Otro..." }));
        jPanel5.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 250, 30));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel17.setText("Nombre del dueño:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 180, -1));

        txtNombre.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel5.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 220, 30));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel20.setText("Seleccione la edad de su mascota:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        comboEdad.setBackground(new java.awt.Color(255, 255, 255));
        comboEdad.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 año", "2 años", "3 años", "4 años", "5 años", "6 o más años" }));
        comboEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEdadActionPerformed(evt);
            }
        });
        jPanel5.add(comboEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 240, 30));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel19.setText("Ingrese su apellido:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        txtApellido.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel5.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 220, 30));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel22.setText("Motivo de la consulta");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        comboMotivo.setBackground(new java.awt.Color(255, 255, 255));
        comboMotivo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consulta - $40.000", "Vacunacion - $80.000", "Esterilizacion - $170.000", "Laboratorio - $20.000-$50.000", "Peluqueria y baño - $45.000" }));
        jPanel5.add(comboMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, 30));

        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel25.setText("Seleccione la fecha y hora de la consulta:");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel5.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 220, 30));

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel26.setText("Ingrese el nombre de su mascota:");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 330, -1));

        txtMascota.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel5.add(txtMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 220, 30));

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel27.setText("Veterinario:");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, 180, -1));

        comboVet.setBackground(new java.awt.Color(255, 255, 255));
        comboVet.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVetActionPerformed(evt);
            }
        });
        jPanel5.add(comboVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, 280, 30));

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel28.setText("Seleccione que tipo de animal es:");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel37.setText("Nro de documento:");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, 30));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 170, 30));

        comboHora.setBackground(new java.awt.Color(255, 255, 255));
        comboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel5.add(comboHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 170, 30));

        jLabel38.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel38.setText("Nro de documento:");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, 30));
        jPanel5.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 20, 770, 720));
        jPanel5.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 280, 730));

        jScrollPane2.setViewportView(jPanel5);

        jTabbedPane1.addTab("tab4", jScrollPane2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultar1.setBackground(new java.awt.Color(196, 154, 237));
        consultar1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        consultar1.setText("Consultar");
        consultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar1ActionPerformed(evt);
            }
        });
        jPanel7.add(consultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 3, 50)); // NOI18N
        jLabel11.setText("Agenda de consulta previa");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel14.setText("Nro de documento:");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        txtDocumento1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtDocumento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumento1ActionPerformed(evt);
            }
        });
        jPanel7.add(txtDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 190, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel12.setText("Nombre del dueño:");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        txtNombre1.setEditable(false);
        txtNombre1.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel7.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 190, -1));

        jLabel33.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel33.setText("Edad de la mascota:");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        txtEdad.setEditable(false);
        txtEdad.setBackground(new java.awt.Color(255, 255, 255));
        txtEdad.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel7.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 190, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel13.setText("Apellido del dueño:");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        txtApellido1.setEditable(false);
        txtApellido1.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });
        jPanel7.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 190, -1));

        jLabel32.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel32.setText("MOTIVO DE LA CONSULTA:");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        txtMotivo.setEditable(false);
        txtMotivo.setBackground(new java.awt.Color(255, 255, 255));
        txtMotivo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel7.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 340, 30));

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel24.setText("Nro de telefono:");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        txtTelefono1.setEditable(false);
        txtTelefono1.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefono1ActionPerformed(evt);
            }
        });
        jPanel7.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 190, -1));

        jLabel31.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel31.setText("Fecha y hora de la cita:");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        hora.setEditable(false);
        hora.setBackground(new java.awt.Color(255, 255, 255));
        hora.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });
        jPanel7.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 190, -1));

        jLabel34.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel34.setText("Tipo de mascota:");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        txtTipo.setEditable(false);
        txtTipo.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });
        jPanel7.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 190, -1));

        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel30.setText("Veterinario(a):");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, -1, -1));

        txtVeterinario.setEditable(false);
        txtVeterinario.setBackground(new java.awt.Color(255, 255, 255));
        txtVeterinario.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeterinarioActionPerformed(evt);
            }
        });
        jPanel7.add(txtVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 190, -1));
        jPanel7.add(imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -30, 740, 720));
        jPanel7.add(imagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 690));

        fecha1.setEditable(false);
        fecha1.setBackground(new java.awt.Color(255, 255, 255));
        fecha1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha1ActionPerformed(evt);
            }
        });
        jPanel7.add(fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 190, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 908, -1));

        jScrollPane3.setViewportView(jPanel3);

        jTabbedPane1.addTab("tab5", jScrollPane3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 847, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void comboEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEdadActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void comboVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVetActionPerformed

    private void txtDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumento1ActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void txtTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono1ActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVeterinarioActionPerformed

    private void txtDocumento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumento2ActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        
    }//GEN-LAST:event_consultarActionPerformed

    private void consultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultar1ActionPerformed

    private void consultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultar2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
          jTabbedPane1.setSelectedIndex(1);
       
    }//GEN-LAST:event_jButton4MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioCliente(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEdad;
    private javax.swing.JComboBox<String> comboHora;
    private javax.swing.JComboBox<String> comboMotivo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboVet;
    private javax.swing.JButton consultar;
    private javax.swing.JButton consultar1;
    private javax.swing.JButton consultar2;
    private javax.swing.JTextField fecha1;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel imagen4;
    private javax.swing.JLabel imagen5;
    private javax.swing.JLabel imagen6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtDocumento1;
    private javax.swing.JTextField txtDocumento2;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtVeterinario;
    // End of variables declaration//GEN-END:variables
}
