/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.*;
import javax.swing.*;


/**
 *
 * @author aylee
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Rmascota = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        Rdueno = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        nombre1 = new javax.swing.JTextField();
        a1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        a2 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JTextField();
        a3 = new javax.swing.JLabel();
        nombre4 = new javax.swing.JTextField();
        a4 = new javax.swing.JLabel();
        nombre5 = new javax.swing.JTextField();
        a5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        a7 = new javax.swing.JLabel();
        nombre6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_imgs/aylen 100 x 100.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, 100));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 22, 57));
        jLabel3.setText("Vet Animalslove");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 220, 40));

        Rmascota.setBackground(new java.awt.Color(196, 154, 237));
        Rmascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_imgs/circulo.png"))); // NOI18N
        jPanel1.add(Rmascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 40, 30));

        boton2.setBackground(new java.awt.Color(196, 154, 237));
        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_imgs/circulo.png"))); // NOI18N
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 40, 30));

        Rdueno.setBackground(new java.awt.Color(196, 154, 237));
        Rdueno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_imgs/circulo.png"))); // NOI18N
        jPanel1.add(Rdueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 22, 57));
        jLabel4.setText("Datos personales");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(47, 22, 57));
        jLabel6.setText("Datos de tu mascota");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 180, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_imgs/imagen (2).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 300, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        a.setForeground(new java.awt.Color(0, 0, 0));
        a.setText("Nombre*");
        jPanel3.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 92, 25));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 160, 30));

        nombre1.setBackground(new java.awt.Color(255, 255, 255));
        nombre1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        nombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 160, 30));

        a1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        a1.setForeground(new java.awt.Color(0, 0, 0));
        a1.setText("Apellido*");
        jPanel3.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 92, 25));

        nombre2.setBackground(new java.awt.Color(255, 255, 255));
        nombre2.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        nombre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 170, 30));

        a2.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        a2.setForeground(new java.awt.Color(0, 0, 0));
        a2.setText("Tipo de documento*");
        jPanel3.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 150, 25));

        nombre3.setBackground(new java.awt.Color(255, 255, 255));
        nombre3.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        nombre3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, 30));

        a3.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        a3.setForeground(new java.awt.Color(0, 0, 0));
        a3.setText("Nro de telefono*");
        jPanel3.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 120, 25));

        nombre4.setBackground(new java.awt.Color(255, 255, 255));
        nombre4.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        nombre4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 160, 30));

        a4.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        a4.setForeground(new java.awt.Color(0, 0, 0));
        a4.setText("Email*");
        jPanel3.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 92, 25));

        nombre5.setBackground(new java.awt.Color(255, 255, 255));
        nombre5.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        nombre5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 160, 30));

        a5.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        a5.setForeground(new java.awt.Color(0, 0, 0));
        a5.setText("Usuario*");
        jPanel3.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 92, 25));

        a6.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        a6.setForeground(new java.awt.Color(0, 0, 0));
        a6.setText("Nro de documento*");
        jPanel3.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 150, 25));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Tarjeta de identidad", "Cedula de extranjeria", " " }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, 30));

        a7.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        a7.setForeground(new java.awt.Color(0, 0, 0));
        a7.setText("Contraseña*");
        jPanel3.add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 92, 25));

        nombre6.setBackground(new java.awt.Color(255, 255, 255));
        nombre6.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        nombre6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 160, 30));

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 640));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 570, 640));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_imgs/nube.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rdueno;
    private javax.swing.JButton Rmascota;
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JButton boton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JTextField nombre;
    javax.swing.JTextField nombre1;
    javax.swing.JTextField nombre2;
    javax.swing.JTextField nombre3;
    javax.swing.JTextField nombre4;
    javax.swing.JTextField nombre5;
    javax.swing.JTextField nombre6;
    // End of variables declaration//GEN-END:variables
}
